[versions]
agp = "8.8.2"
appcompat = "1.6.1"
material = "1.10.0"
cardview = "1.0.0"
recyclerview = "1.3.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
